use noce;
DROP TABLE IF EXISTS `wid_maxact_day_weekmaxdaymin`;
CREATE EXTERNAL TABLE `wid_maxact_day_weekmaxdaymin`(
    `city_id`                            int,
    `base_statn_id`                      int,
    `base_statn_name`                    string,
    `cell_id`                            int,
    `cell_name`                          string,
    `bs_vendor`                          string,
    `is_indoor`                          string,
    `band`                               string,
    `system_type_or_standard`            string,
    `region`                             string,
    `attribute`                          bigint,
    `nb_flag`                            tinyint,
    `band_width`                         int,
    `maxactH00`                           float,
    `maxactH01`                           float,
    `maxactH02`                           float,
    `maxactH03`                           float,
    `maxactH04`                           float,
    `maxactH05`                           float,
    `maxactH06`                           float,
    `maxactH07`                           float,
    `maxactH08`                           float,
    `maxactH09`                           float,
    `maxactH10`                           float,
    `maxactH11`                           float,
    `maxactH12`                           float,
    `maxactH13`                           float,
    `maxactH14`                           float,
    `maxactH15`                           float,
    `maxactH16`                           float,
    `maxactH17`                           float,
    `maxactH18`                           float,
    `maxactH19`                           float,
    `maxactH20`                           float,
    `maxactH21`                           float,
    `maxactH22`                           float,
    `maxactH23`                           float,
    `maxactH00_fill`                      float,
    `maxactH01_fill`                      float,
    `maxactH02_fill`                      float,
    `maxactH03_fill`                      float,
    `maxactH04_fill`                      float,
    `maxactH05_fill`                      float,
    `maxactH06_fill`                      float,
    `maxactH07_fill`                      float,
    `maxactH08_fill`                      float,
    `maxactH09_fill`                      float,
    `maxactH10_fill`                      float,
    `maxactH11_fill`                      float,
    `maxactH12_fill`                      float,
    `maxactH13_fill`                      float,
    `maxactH14_fill`                      float,
    `maxactH15_fill`                      float,
    `maxactH16_fill`                      float,
    `maxactH17_fill`                      float,
    `maxactH18_fill`                      float,
    `maxactH19_fill`                      float,
    `maxactH20_fill`                      float,
    `maxactH21_fill`                      float,
    `maxactH22_fill`                      float,
    `maxactH23_fill`                      float,
    `maxact24hflag`                       tinyint,
    `maxact24hfullflag`                   tinyint,
    `maxactmin`                           float,
    `maxactmax`                           float,
    `maxactsum`                           float,
    `maxactmean`                          float,
    `maxactmedian`                        float,
    `maxactvar`                           float,
    `maxactstd`                           float,
    `maxactidxmax`                        string,
    `maxactidxmin`                        string,
    `maxactcv`                            float,
    `zero_actuser_period`                 string,
    `less_actuser_period`                 string,
    `maxact_x_score00`                    float,
    `maxact_x_score01`                    float,
    `maxact_x_score02`                    float,
    `maxact_x_score03`                    float,
    `maxact_x_score04`                    float,
    `maxact_x_score05`                    float,
    `maxact_x_score06`                    float,
    `maxact_x_score07`                    float,
    `maxact_x_score08`                    float,
    `maxact_x_score09`                    float,
    `maxact_x_score10`                    float,
    `maxact_x_score11`                    float,
    `maxact_x_score12`                    float,
    `maxact_x_score13`                    float,
    `maxact_x_score14`                    float,
    `maxact_x_score15`                    float,
    `maxact_x_score16`                    float,
    `maxact_x_score17`                    float,
    `maxact_x_score18`                    float,
    `maxact_x_score19`                    float,
    `maxact_x_score20`                    float,
    `maxact_x_score21`                    float,
    `maxact_x_score22`                    float,
    `maxact_x_score23`                    float,
    `peak`                                string       comment '波峰',
    `peak_mean`                           float        comment '波峰均值',
    `peak_max`                            float        comment '波峰极大值',
    `peak_x_score`                        float        comment '波峰系数',
    `peak_core`                           string       comment '波峰核心周期',
    `trough`                              string       comment '波谷',
    `trough_mean`                         float        comment '波谷均值',
    `trough_max`                          float        comment '波谷极大值',
    `trough_x_score`                      float        comment '波谷系数',
    `trough_core`                         string       comment '波谷核心周期',
    `near_stable_1st`                     string,
    `near_stable_1st_mean`                float,
    `near_stable_1st_max`                 float,
    `near_stable_1st_x_score`             float,
    `near_stable_2nd`                     string,
    `near_stable_2nd_mean`                float,
    `near_stable_2nd_max`                 float,
    `near_stable_2nd_x_score`             float,
    `near_stable_3rd`                     string,
    `near_stable_3rd_mean`                float,
    `near_stable_3rd_max`                 float,
    `near_stable_3rd_x_score`             float,
    `near_stable_contain_trough`          string,
    `near_stable_contain_trough_mean`     float,
    `near_stable_contain_trough_max`      float,
    `near_stable_contain_trough_x_score`  float,
    `day_of_week`                         int          comment '周几'
)
PARTITIONED BY (`day` bigint)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'='|', 'serialization.format'='|')
STORED AS INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION 'hdfs://noce1/DATA/PUBLIC/WID/WID_MAXACT_DAY_WEEKMAXDAYMIN'