use noce;
DROP TABLE IF EXISTS `wid_dwprb_day_weekmaxdaymin`;
CREATE EXTERNAL TABLE `wid_dwprb_day_weekmaxdaymin`(
    `city_id`                            int,
    `base_statn_id`                      int,
    `base_statn_name`                    string,
    `cell_id`                            int,
    `cell_name`                          string,
    `bs_vendor`                          string,
    `is_indoor`                          string,
    `band`                               string,
    `system_type_or_standard`            string,
    `region`                             string,
    `attribute`                          bigint,
    `nb_flag`                            tinyint,
    `band_width`                         int,
    `dwprbH00`                           float,
    `dwprbH01`                           float,
    `dwprbH02`                           float,
    `dwprbH03`                           float,
    `dwprbH04`                           float,
    `dwprbH05`                           float,
    `dwprbH06`                           float,
    `dwprbH07`                           float,
    `dwprbH08`                           float,
    `dwprbH09`                           float,
    `dwprbH10`                           float,
    `dwprbH11`                           float,
    `dwprbH12`                           float,
    `dwprbH13`                           float,
    `dwprbH14`                           float,
    `dwprbH15`                           float,
    `dwprbH16`                           float,
    `dwprbH17`                           float,
    `dwprbH18`                           float,
    `dwprbH19`                           float,
    `dwprbH20`                           float,
    `dwprbH21`                           float,
    `dwprbH22`                           float,
    `dwprbH23`                           float,
    `dwprbH00_fill`                      float,
    `dwprbH01_fill`                      float,
    `dwprbH02_fill`                      float,
    `dwprbH03_fill`                      float,
    `dwprbH04_fill`                      float,
    `dwprbH05_fill`                      float,
    `dwprbH06_fill`                      float,
    `dwprbH07_fill`                      float,
    `dwprbH08_fill`                      float,
    `dwprbH09_fill`                      float,
    `dwprbH10_fill`                      float,
    `dwprbH11_fill`                      float,
    `dwprbH12_fill`                      float,
    `dwprbH13_fill`                      float,
    `dwprbH14_fill`                      float,
    `dwprbH15_fill`                      float,
    `dwprbH16_fill`                      float,
    `dwprbH17_fill`                      float,
    `dwprbH18_fill`                      float,
    `dwprbH19_fill`                      float,
    `dwprbH20_fill`                      float,
    `dwprbH21_fill`                      float,
    `dwprbH22_fill`                      float,
    `dwprbH23_fill`                      float,
    `dwprb24hflag`                       tinyint,
    `dwprb24hfullflag`                   tinyint,
    `dwprbmin`                           float,
    `dwprbmax`                           float,
    `dwprbsum`                           float,
    `dwprbmean`                          float,
    `dwprbmedian`                        float,
    `dwprbvar`                           float,
    `dwprbstd`                           float,
    `dwprbidxmax`                        string,
    `dwprbidxmin`                        string,
    `dwprbcv`                            float,
    `low1_dwprb_period`                  string,
    `low2_dwprb_period`                  string,
    `low3_dwprb_period`                  string,
    `low4_dwprb_period`                  string,
    `low5_dwprb_period`                  string,
    `low6_dwprb_period`                  string,
    `low7_dwprb_period`                  string,
    `low8_dwprb_period`                  string,
    `dwprb_x_score00`                    float,
    `dwprb_x_score01`                    float,
    `dwprb_x_score02`                    float,
    `dwprb_x_score03`                    float,
    `dwprb_x_score04`                    float,
    `dwprb_x_score05`                    float,
    `dwprb_x_score06`                    float,
    `dwprb_x_score07`                    float,
    `dwprb_x_score08`                    float,
    `dwprb_x_score09`                    float,
    `dwprb_x_score10`                    float,
    `dwprb_x_score11`                    float,
    `dwprb_x_score12`                    float,
    `dwprb_x_score13`                    float,
    `dwprb_x_score14`                    float,
    `dwprb_x_score15`                    float,
    `dwprb_x_score16`                    float,
    `dwprb_x_score17`                    float,
    `dwprb_x_score18`                    float,
    `dwprb_x_score19`                    float,
    `dwprb_x_score20`                    float,
    `dwprb_x_score21`                    float,
    `dwprb_x_score22`                    float,
    `dwprb_x_score23`                    float,
    `peak`                               string       comment '波峰',
    `peak_mean`                          float        comment '波峰均值',
    `peak_max`                           float        comment '波峰极大值',
    `peak_x_score`                       float        comment '波峰系数',
    `peak_core`                          string       comment '波峰核心周期',
    `trough`                             string       comment '波谷',
    `trough_mean`                        float        comment '波谷均值',
    `trough_max`                         float        comment '波谷极大值',
    `trough_x_score`                     float        comment '波谷系数',
    `trough_core`                        string       comment '波谷核心周期',
    `near_stable_1st`                    string,
    `near_stable_1st_mean`               float,
    `near_stable_1st_max`                float,
    `near_stable_1st_x_score`            float,
    `near_stable_2nd`                    string,
    `near_stable_2nd_mean`               float,
    `near_stable_2nd_max`                float,
    `near_stable_2nd_x_score`            float,
    `near_stable_3rd`                    string,
    `near_stable_3rd_mean`               float,
    `near_stable_3rd_max`                float,
    `near_stable_3rd_x_score`            float,
    `near_stable_contain_trough`         string,
    `near_stable_contain_trough_mean`    float,
    `near_stable_contain_trough_max`     float,
    `near_stable_contain_trough_x_score` float,
    `day_of_week`                        int          comment '周几'
)
PARTITIONED BY (`day` bigint)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim'='|', 'serialization.format'='|') 
STORED AS INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat' 
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION 'hdfs://noce1/DATA/PUBLIC/WID/WID_DWPRB_DAY_WEEKMAXDAYMIN'