use noce;

DROP TABLE IF EXISTS `wid_upprb_x_jc_day`;

CREATE EXTERNAL TABLE `wid_upprb_x_jc_day`(
    `city_id` int,
    `base_statn_id` int,
    `base_statn_name` string,
    `cell_id` int,
    `cell_name` string,
    `bs_vendor` string,
    `is_indoor` string,
    `band` string,
    `system_type_or_standard` string,
    `region` string,
    `attribute` bigint,
    `nb_flag` tinyint,
    `band_width` int,
    `upprbH00` float,
    `upprbH01` float,
    `upprbH02` float,
    `upprbH03` float,
    `upprbH04` float,
    `upprbH05` float,
    `upprbH06` float,
    `upprbH07` float,
    `upprbH08` float,
    `upprbH09` float,
    `upprbH10` float,
    `upprbH11` float,
    `upprbH12` float,
    `upprbH13` float,
    `upprbH14` float,
    `upprbH15` float,
    `upprbH16` float,
    `upprbH17` float,
    `upprbH18` float,
    `upprbH19` float,
    `upprbH20` float,
    `upprbH21` float,
    `upprbH22` float,
    `upprbH23` float,
    `upprbmin` float,
    `upprbmax` float,
    `upprbsum` float,
    `upprbmean` float,
    `upprbmedian` float,
    `upprbvar` float,
    `upprbstd` float,
    `upprbidxmax` string,
    `upprbidxmin` string,
    `upprbcv` float,
    `upprbscore00` int,
    `upprbscore01` int,
    `upprbscore02` int,
    `upprbscore03` int,
    `upprbscore04` int,
    `upprbscore05` int,
    `upprbscore06` int,
    `upprbscore07` int,
    `upprbscore08` int,
    `upprbscore09` int,
    `upprbscore10` int,
    `upprbscore11` int,
    `upprbscore12` int,
    `upprbscore13` int,
    `upprbscore14` int,
    `upprbscore15` int,
    `upprbscore16` int,
    `upprbscore17` int,
    `upprbscore18` int,
    `upprbscore19` int,
    `upprbscore20` int,
    `upprbscore21` int,
    `upprbscore22` int,
    `upprbscore23` int,
    `trough` string
)
PARTITIONED BY (`day` bigint)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe' 
WITH SERDEPROPERTIES ('field.delim'='|', 'serialization.format'='|') 
STORED AS INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat' 
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION 'hdfs://noce1/DATA/PUBLIC/WID/WID_UPPRB_X_JC_DAY'