use noce;

DROP TABLE IF EXISTS `wid_maxact_x_jc_day`;

CREATE EXTERNAL TABLE `wid_maxact_x_jc_day`(
    `city_id` int,
    `base_statn_id` int,
    `base_statn_name` string,
    `cell_id` int,
    `cell_name` string,
    `bs_vendor` string,
    `is_indoor` string,
    `band` string,
    `system_type_or_standard` string,
    `region` string,
    `attribute` bigint,
    `nb_flag` tinyint,
    `band_width` int,
    `maxactH00` float,
    `maxactH01` float,
    `maxactH02` float,
    `maxactH03` float,
    `maxactH04` float,
    `maxactH05` float,
    `maxactH06` float,
    `maxactH07` float,
    `maxactH08` float,
    `maxactH09` float,
    `maxactH10` float,
    `maxactH11` float,
    `maxactH12` float,
    `maxactH13` float,
    `maxactH14` float,
    `maxactH15` float,
    `maxactH16` float,
    `maxactH17` float,
    `maxactH18` float,
    `maxactH19` float,
    `maxactH20` float,
    `maxactH21` float,
    `maxactH22` float,
    `maxactH23` float,
    `maxactmin` float,
    `maxactmax` float,
    `maxactsum` float,
    `maxactmean` float,
    `maxactmedian` float,
    `maxactvar` float,
    `maxactstd` float,
    `maxactidxmax` string,
    `maxactidxmin` string,
    `maxactcv` float,
    `maxactscore00` int,
    `maxactscore01` int,
    `maxactscore02` int,
    `maxactscore03` int,
    `maxactscore04` int,
    `maxactscore05` int,
    `maxactscore06` int,
    `maxactscore07` int,
    `maxactscore08` int,
    `maxactscore09` int,
    `maxactscore10` int,
    `maxactscore11` int,
    `maxactscore12` int,
    `maxactscore13` int,
    `maxactscore14` int,
    `maxactscore15` int,
    `maxactscore16` int,
    `maxactscore17` int,
    `maxactscore18` int,
    `maxactscore19` int,
    `maxactscore20` int,
    `maxactscore21` int,
    `maxactscore22` int,
    `maxactscore23` int,
    `idleflag` int,
    `trough` string
)
PARTITIONED BY (`day` bigint)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe' 
WITH SERDEPROPERTIES ('field.delim'='|', 'serialization.format'='|') 
STORED AS INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat' 
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION 'hdfs://noce1/DATA/PUBLIC/WID/WID_MAXACT_X_JC_DAY'