use noce;

DROP TABLE IF EXISTS `wid_maxrrc_x_jc_day`;

CREATE EXTERNAL TABLE `wid_maxrrc_x_jc_day`(
    `city_id` int,
    `base_statn_id` int,
    `base_statn_name` string,
    `cell_id` int,
    `cell_name` string,
    `bs_vendor` string,
    `is_indoor` string,
    `band` string,
    `system_type_or_standard` string,
    `region` string,
    `attribute` bigint,
    `nb_flag` tinyint,
    `band_width` int,
    `maxrrcH00` float,
    `maxrrcH01` float,
    `maxrrcH02` float,
    `maxrrcH03` float,
    `maxrrcH04` float,
    `maxrrcH05` float,
    `maxrrcH06` float,
    `maxrrcH07` float,
    `maxrrcH08` float,
    `maxrrcH09` float,
    `maxrrcH10` float,
    `maxrrcH11` float,
    `maxrrcH12` float,
    `maxrrcH13` float,
    `maxrrcH14` float,
    `maxrrcH15` float,
    `maxrrcH16` float,
    `maxrrcH17` float,
    `maxrrcH18` float,
    `maxrrcH19` float,
    `maxrrcH20` float,
    `maxrrcH21` float,
    `maxrrcH22` float,
    `maxrrcH23` float,
    `maxrrcmin` float,
    `maxrrcmax` float,
    `maxrrcsum` float,
    `maxrrcmean` float,
    `maxrrcmedian` float,
    `maxrrcvar` float,
    `maxrrcstd` float,
    `maxrrcidxmax` string,
    `maxrrcidxmin` string,
    `maxrrccv` float,
    `maxrrcscore00` int,
    `maxrrcscore01` int,
    `maxrrcscore02` int,
    `maxrrcscore03` int,
    `maxrrcscore04` int,
    `maxrrcscore05` int,
    `maxrrcscore06` int,
    `maxrrcscore07` int,
    `maxrrcscore08` int,
    `maxrrcscore09` int,
    `maxrrcscore10` int,
    `maxrrcscore11` int,
    `maxrrcscore12` int,
    `maxrrcscore13` int,
    `maxrrcscore14` int,
    `maxrrcscore15` int,
    `maxrrcscore16` int,
    `maxrrcscore17` int,
    `maxrrcscore18` int,
    `maxrrcscore19` int,
    `maxrrcscore20` int,
    `maxrrcscore21` int,
    `maxrrcscore22` int,
    `maxrrcscore23` int,
    `idleflag` int,
    `trough` string
)
PARTITIONED BY (`day` bigint)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe' 
WITH SERDEPROPERTIES ('field.delim'='|', 'serialization.format'='|') 
STORED AS INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat' 
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION 'hdfs://noce1/DATA/PUBLIC/WID/WID_MAXRRC_X_JC_DAY'