use noce;

DROP TABLE IF EXISTS `wid_dwprb_x_jc_day`;

CREATE EXTERNAL TABLE `wid_dwprb_x_jc_day`(
    `city_id` int,
    `base_statn_id` int,
    `base_statn_name` string,
    `cell_id` int,
    `cell_name` string,
    `bs_vendor` string,
    `is_indoor` string,
    `band` string,
    `system_type_or_standard` string,
    `region` string,
    `attribute` bigint,
    `nb_flag` tinyint,
    `band_width` int,
    `dwprbH00` float,
    `dwprbH01` float,
    `dwprbH02` float,
    `dwprbH03` float,
    `dwprbH04` float,
    `dwprbH05` float,
    `dwprbH06` float,
    `dwprbH07` float,
    `dwprbH08` float,
    `dwprbH09` float,
    `dwprbH10` float,
    `dwprbH11` float,
    `dwprbH12` float,
    `dwprbH13` float,
    `dwprbH14` float,
    `dwprbH15` float,
    `dwprbH16` float,
    `dwprbH17` float,
    `dwprbH18` float,
    `dwprbH19` float,
    `dwprbH20` float,
    `dwprbH21` float,
    `dwprbH22` float,
    `dwprbH23` float,
    `dwprbmin` float,
    `dwprbmax` float,
    `dwprbsum` float,
    `dwprbmean` float,
    `dwprbmedian` float,
    `dwprbvar` float,
    `dwprbstd` float,
    `dwprbidxmax` string,
    `dwprbidxmin` string,
    `dwprbcv` float,
    `dwprbscore00` int,
    `dwprbscore01` int,
    `dwprbscore02` int,
    `dwprbscore03` int,
    `dwprbscore04` int,
    `dwprbscore05` int,
    `dwprbscore06` int,
    `dwprbscore07` int,
    `dwprbscore08` int,
    `dwprbscore09` int,
    `dwprbscore10` int,
    `dwprbscore11` int,
    `dwprbscore12` int,
    `dwprbscore13` int,
    `dwprbscore14` int,
    `dwprbscore15` int,
    `dwprbscore16` int,
    `dwprbscore17` int,
    `dwprbscore18` int,
    `dwprbscore19` int,
    `dwprbscore20` int,
    `dwprbscore21` int,
    `dwprbscore22` int,
    `dwprbscore23` int,
    `trough` string
)
PARTITIONED BY (`day` bigint)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe' 
WITH SERDEPROPERTIES ('field.delim'='|', 'serialization.format'='|') 
STORED AS INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat' 
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION 'hdfs://noce1/DATA/PUBLIC/WID/WID_DWPRB_X_JC_DAY'